name: Publish Package to npmjs

on:
  push:
    branches:
      - main 

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Publish package with retry
        run: |
          max_retries=3
          counter=0
          until [ $counter -ge $max_retries ]
          do
            npm publish && break
            counter=$((counter+1))
            echo "Publish failed... retrying in 30 seconds ($counter/$max_retries)"
            sleep 30
          done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
